### ISSUE TITLE
update to lagom 1.6.5

### ISSUE THREAD

**Issue by an-tex** [mliarakos/lagom-js#23]
I've already prepared a [PR on akka.js](https://github.com/akka-js/akka.js/pull/127) to update it to 2.6.14. I guess that's a dependency for lagom.js 1.6.5?

**Comment by mliarakos** [comment]
Yes, it's a dependency for lagom.js 1.6.5. I pushed #24 for the upgrade to Lagom 1.6.5.

**Comment by mliarakos** [comment]
Fixed by #24.
