### ISSUE TITLE
Update to lagom 1.5.5

### ISSUE THREAD

**Issue by an-tex** [mliarakos/lagom-js#3]
https://github.com/lagom/lagom/releases/tag/1.5.5

I'd be happy to assist with some guidance.

**Comment by mliarakos** [comment]
Released [0.1.1-1.5.5](https://github.com/mliarakos/lagom-js/releases/tag/0.1.1-1.5.5).

**Comment by mliarakos** [comment]
The basic process I go through for a new version of Lagom is:

- Update `baseLagomVersion` in `build.sbt`
- Review the commits for the new version of Lagom and check if any of the lagom.js specific source files need to be updated to reflect upstream Lagom changes
- Update the versions of sbt, plugins, and dependencies, keeping dependencies shared with Lagom at the same version as Lagom (e.g., `play-json`, `scalatest`)
- Run tests in sbt with: `+test`
- Check that the [demo](https://github.com/mliarakos/lagom-scalajs-example) works with the new version, generally by using a locally published snapshot

If you're reusing a previous git repository, it's a good idea to run `+clean` and `cleanLagomLibrary` first.
