### ISSUE TITLE
Update to lagom 1.6.0

### ISSUE THREAD

**Issue by an-tex** [mliarakos/lagom-js#4]
https://www.lagomframework.com/documentation/1.6.x/java/Migration16.html
https://github.com/lagom/lagom/releases/tag/1.6.0

I guess we need to wait for https://github.com/akka-js/akka.js/issues/103 first. After that I'd be happy to assist here too :)

**Comment by mliarakos** [comment]
I haven't looked too deeply at what's needed for Lagom 1.6, but I'm hoping it won't be too bad since a lot of the big Lagom 1.6 features are for the backend service implementation. However, you're right that we'll need akka.js 2.6 to get started.

**Comment by an-tex** [comment]
A snapshot version of akka.js 2.6.1 is available https://github.com/akka-js/akka.js/issues/103#issuecomment-568295012. I'll try to port lagom.js to test it with that.

**Comment by an-tex** [comment]
I didn't get too far but I hope that's still worth starting with ;) https://github.com/mliarakos/lagom-js/pull/5

**Comment by mliarakos** [comment]
Released [0.2.0-1.6.0](https://github.com/mliarakos/lagom-js/releases/tag/0.2.0-1.6.0).
