### ISSUE TITLE
Scala 2.13 Support

### ISSUE THREAD

**Issue by mliarakos** [mliarakos/lagom-js#6]
Update lagom.js to support Scala 2.13.

Lagom.js depends on Akka.js, which is still working on Scala 2.13 support (see this [comment](https://github.com/akka-js/akka.js/issues/103#issuecomment-568295012) in https://github.com/akka-js/akka.js/issues/103).

Once that is resolved it should be as simple as adding Scala 2.13 to `scalaVersions` in `build.sbt`:

```scala
val scalaVersions = Seq("2.12.10", "2.13.1")
```

**Comment by andreaTP** [comment]
just to keep you updated, I started https://github.com/akka-js/akka.js/pull/112

**Comment by mliarakos** [comment]
@andreaTP, thanks!

**Comment by mliarakos** [comment]
See https://github.com/mliarakos/lagom-js/pull/9.
